services:
  ai-sentinel-db:
    image: postgres:18
    container_name: ai-sentinel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai-sentinel
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ../init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai-sentinel"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sentinel-db-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-sentinel
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - ai-sentinel-db
    networks:
      - sentinel-db-network

volumes:
  postgres-data:
    name: sentinel-db-data
  pgadmin-data:
    name: sentinel-pgadmin-data

networks:
  sentinel-db-network:
    name: sentinel-db-network
